### ISSUE TITLE
not an issue - fyi

### ISSUE THREAD

**Issue by 8secz-johndpope** [RussellSB/voice-conversion-gan#2]
Hi @RussellSB 

there was a Voice Conversion Challenge 2020 baseline: CycleVAE w/ PWG vocoder
Official homepage: http://www.vc-challenge.org/

some code was provided by @bigpon / perhaps it could help the training / getting started stuff.
 https://github.com/bigpon/vcc20_baseline_cyclevae/tree/master/baseline
https://github.com/bigpon/vcc20_baseline_cyclevae/blob/master/baseline/src/parallel_wavegan/models/melgan.py

In the paper it mentions Google's Parratron
this was implemented by @fd873630 / his models are here ( could this help?)
https://github.com/fd873630/Parrotron/tree/master/models

I wonder if a bit of detective work can piece things together to avoid the mode collapse.
Otherwise need to wait for @ebadawy to release code.

**Comment by RussellSB** [comment]
Cheers for the tips! :) Soon getting back to resuming progress on this project, so I'll be sure to check this out.

I've actually managed to overcome the mode collapse issue I was facing - mainly changing the MSE loss to L1 loss for the reconstruction error was what made the difference (the prior to the KLD loss for the VAE).

Right now it seems to be much more effective - but the training is a bit unstable and sometimes it regresses to learning how to reconstruct the input rather than transfer style to a diff melspectrogram type. But Ive only tested it with a BCE adversarial loss and yet to try out MSE and potentially WSE so! We'll see how things go :) - will nonetheless keep my eyes on these repos. Seriously, thanks for sharing.

Kind regards,
Russell

**Comment by 8secz-johndpope** [comment]
do you have any sample / demo / google drive link?

**Comment by RussellSB** [comment]
Sure! Here are some demo files I organised with the version of a month ago https://drive.google.com/file/d/1ZHzYvfN_dvZaKuRAdnKUyZ5TL3_JNtxY/view?usp=sharing

This was when the model was configured with 2 residual blocks. At this state, only B2A mappings with BCE worked. Now with 3 residual blocks, A2B also works., and MSE seems to achieve better results that BCE.

More or less the added residual block avoids an error case where it focuses too much on the reconstruction. The sound quality atm is currently like what you hear for B2A BCE in the above.

I'm planning to see if changing resblock designs may improve things. Like to what extent I can stack on more resblocks - given my computation budget - while still avoiding significant vanishing gradients

**Comment by 8secz-johndpope** [comment]
Thanks 🙏
