### ISSUE TITLE
Quick Question regarding convert mel_spectrogram to wav

### ISSUE THREAD

**Issue by ybjoe** [RussellSB/voice-conversion-gan#3]
Hello, Thank you for your great implementation work!

I have a quick question about converting from mel-spectrogram to wav.

I have checked that you used librosa library to convert frequency domain to time domain.

Have you tried to use any other libraries such as torchaudio which support GPU? because it takes so long time to convert mel-spectrograms to wav... 

Thank you!

**Comment by RussellSB** [comment]
Hi YB-Joe,

Not a problem! Thanks so much for your feedback :) ... the Griffin Lim reconstructions via librosa are quite a bottleneck. I haven't heard of torch audio's implementation before - cool that it supports GPU. I'll be sure to check this out when I can. 

Kind regards,
Russell

**Comment by ybjoe** [comment]
Thank you! 👍

**Comment by RussellSB** [comment]
Thanks for closing this YB-Joe, but I'll re-open this till I find the time to address this and keep you posted once I do

**Comment by RussellSB** [comment]
@YB-Joe sorry I haven't really had the time to get into this, and rerunning the inference with new resources the bottleneck of this issue is less grave than I thought.  I'm closing this just to give some priority to other issues, I hope this is fine with you. Of course, will leave this here. 

This discussion is useful for those having limited access to CPU resources (as I previously did when persuing this project from a shared student server).

To whoever is reading this and would like to consider creating a pull request with such a feature please consider doing so on the originating repo for voice conversion [here](https://github.com/ebadawy/voice_conversion).
