### ISSUE TITLE
about calculate KLD

### ISSUE THREAD

**Issue by FlyToYourMooN** [RussellSB/voice-conversion-gan#4]
Hello! Your excellent work has benefited me a lot in the introduction of timbre conversion, but I don't understand one thing well: when you calculate KLD, put the square of each potential variable and then get the average value as the loss of KLD. I haven't understood it here. Could you explain it? Thank you very much!

**Comment by RussellSB** [comment]
Hi! Glad to hear. At the latent space. there is assumed to be a unit variance with a zero-mean Gaussian distribution, and because of this - KLD can be computed in such a way. From what I understood this is a trick to reducing complexity a little bit. 

Early on in this project I tried experimenting with this approach for KLD and more standard ways (with an estimated log variance rather than unit log variance). Results-wise I couldn't find much of a difference and decided to stick with this unit approach since that's what the originating work UNIT followed. Y

ou can find the first use case of this approach here in UNITs repo (lines 255-257): https://github.com/mingyuliutw/UNIT/blob/master/trainer.py

**Comment by FlyToYourMooN** [comment]
Thank you for your answer! I seem to understand
